// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBDg7jeVHcgwQjv5NP1uELQyDAQstGBc',
    appId: '1:397710890035:web:e35bc4fc61b5479ae23f46',
    messagingSenderId: '397710890035',
    projectId: 'skin-5dc25',
    authDomain: 'skin-5dc25.firebaseapp.com',
    storageBucket: 'skin-5dc25.appspot.com',
    measurementId: 'G-YR77XMH6ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2iwtOKnbKE15iWkFuOpC1CXVXV9QgcFo',
    appId: '1:397710890035:android:e42c26fec8761b85e23f46',
    messagingSenderId: '397710890035',
    projectId: 'skin-5dc25',
    storageBucket: 'skin-5dc25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMp6D0yW2FILBDF1r364JiKJTVJjtna4',
    appId: '1:397710890035:ios:cb36c68eea817f43e23f46',
    messagingSenderId: '397710890035',
    projectId: 'skin-5dc25',
    storageBucket: 'skin-5dc25.appspot.com',
    iosBundleId: 'com.example.skin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMp6D0yW2FILBDF1r364JiKJTVJjtna4',
    appId: '1:397710890035:ios:cb36c68eea817f43e23f46',
    messagingSenderId: '397710890035',
    projectId: 'skin-5dc25',
    storageBucket: 'skin-5dc25.appspot.com',
    iosBundleId: 'com.example.skin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBDg7jeVHcgwQjv5NP1uELQyDAQstGBc',
    appId: '1:397710890035:web:32c25aac962c9460e23f46',
    messagingSenderId: '397710890035',
    projectId: 'skin-5dc25',
    authDomain: 'skin-5dc25.firebaseapp.com',
    storageBucket: 'skin-5dc25.appspot.com',
    measurementId: 'G-M2S44BEPH3',
  );
}
